// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbHpkJ95TZdV9XL2UAcxX8DS3Jq8mk6aA',
    appId: '1:974500166498:web:c18a8ed8355f981eb94a3b',
    messagingSenderId: '974500166498',
    projectId: 'flutter-crud-522b1',
    authDomain: 'flutter-crud-522b1.firebaseapp.com',
    storageBucket: 'flutter-crud-522b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQk9VQMc8Xw8whWIWIVypcr8IeaM-0Mp8',
    appId: '1:974500166498:android:7152142bcb36d5dab94a3b',
    messagingSenderId: '974500166498',
    projectId: 'flutter-crud-522b1',
    storageBucket: 'flutter-crud-522b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIY-MJgAGe-gZ1AhaxtEatX-asVfPpTfM',
    appId: '1:974500166498:ios:3e8922e6e1066f44b94a3b',
    messagingSenderId: '974500166498',
    projectId: 'flutter-crud-522b1',
    storageBucket: 'flutter-crud-522b1.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIY-MJgAGe-gZ1AhaxtEatX-asVfPpTfM',
    appId: '1:974500166498:ios:3e8922e6e1066f44b94a3b',
    messagingSenderId: '974500166498',
    projectId: 'flutter-crud-522b1',
    storageBucket: 'flutter-crud-522b1.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbHpkJ95TZdV9XL2UAcxX8DS3Jq8mk6aA',
    appId: '1:974500166498:web:6c6e8a8a263bf421b94a3b',
    messagingSenderId: '974500166498',
    projectId: 'flutter-crud-522b1',
    authDomain: 'flutter-crud-522b1.firebaseapp.com',
    storageBucket: 'flutter-crud-522b1.appspot.com',
  );
}
